# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{nozomi}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh Price"]
  s.date = %q{2011-01-28}
  s.default_executable = %q{nozomi}
  s.description = %q{Opinionated Rails project templating: rspec, haml, sass, compass, etc}
  s.email = %q{joshcp@gmail.com}
  s.executables = ["nozomi"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown",
    "TODO"
  ]
  s.files = [
    "Gemfile",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "TODO",
    "VERSION",
    "bin/nozomi",
    "lib/nozomi.rb",
    "lib/nozomi/cli.rb",
    "lib/nozomi/interactive.rb",
    "lib/nozomi/template.rb",
    "lib/rails3-template.rb",
    "lib/templates/core.rb",
    "lib/templates/cucumber.rb",
    "lib/templates/decent_exposure.rb",
    "lib/templates/devise.rb",
    "lib/templates/fakeweb.rb",
    "lib/templates/formtastic.rb",
    "lib/templates/git.rb",
    "lib/templates/haml-and-compass.rb",
    "lib/templates/jquery.rb",
    "lib/templates/machinist.rb",
    "lib/templates/rspec.rb",
    "lib/templates/standard.rb",
    "nozomi.gemspec"
  ]
  s.homepage = %q{http://github.com/joshprice/nozomi}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Get your rails projects going faster with Nozomi}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 3.0.3"])
      s.add_runtime_dependency(%q<clamp>, ["= 0.1.5"])
      s.add_development_dependency(%q<rake>, ["= 0.8.7"])
      s.add_development_dependency(%q<jeweler>, ["= 1.5.1"])
    else
      s.add_dependency(%q<rails>, ["= 3.0.3"])
      s.add_dependency(%q<clamp>, ["= 0.1.5"])
      s.add_dependency(%q<rake>, ["= 0.8.7"])
      s.add_dependency(%q<jeweler>, ["= 1.5.1"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.0.3"])
    s.add_dependency(%q<clamp>, ["= 0.1.5"])
    s.add_dependency(%q<rake>, ["= 0.8.7"])
    s.add_dependency(%q<jeweler>, ["= 1.5.1"])
  end
end

